{
    "openapi": "3.0.2",
    "info": {
        "title": "recipes-API",
        "version": "1.0.0",
        "description": "### This is a Swagger UI for our Recipes API"
    },
    "paths": {
        "/recipes": {
            "get": {
                "tags": [
                    "recipes"
                ],
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "array",
                                    "items": {
                                        "type": "string"
                                    }
                                },
                                "examples": {
                                    "List of recipes": {
                                        "value": [
                                            "Stuffed Peppers",
                                            "Caesar Salad"
                                        ]
                                    }
                                }
                            }
                        },
                        "description": "Returns a list of recipes"
                    },
                    "400": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "array",
                                    "items": {
                                        "type": "string"
                                    }
                                },
                                "examples": {
                                    "Recipe not found": {
                                        "value": "New recipe was not found. "
                                    }
                                }
                            }
                        },
                        "description": "Bad Request"
                    },
                    "404": {
                        "content": {
                            "application/json": {}
                        },
                        "description": "Recipe was not found"
                    },
                    "500": {
                        "description": "The server encountered an unexpected condition that prevented it from fulfilling the request"
                    }
                },
                "summary": "Get a list of all recipes",
                "description": "Returns a list of all recipes in API"
            },
            "post": {
                "requestBody": {
                    "description": "A new recipe to be created",
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/new-recipe"
                            }
                        }
                    },
                    "required": true
                },
                "tags": [
                    "recipes"
                ],
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/new-recipe"
                                }
                            }
                        },
                        "description": "Request has succeeded"
                    },
                    "201": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/new-recipe"
                                }
                            }
                        },
                        "description": "New recipe has been created"
                    },
                    "400": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/error"
                                }
                            }
                        },
                        "description": "One or all params are missing."
                    },
                    "500": {
                        "description": "The server encountered an unexpected condition that prevented it from fulfilling the request"
                    }
                },
                "summary": "Creates a recipe",
                "description": "Creates a new recipe"
            }
        },
        "/recipes/{id}": {
            "get": {
                "tags": [
                    "recipes"
                ],
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "array",
                                    "items": {
                                        "type": "string"
                                    }
                                },
                                "examples": {
                                    "Full details of a given ": {
                                        "value": {
                                            "id": 1,
                                            "name": "Stuffed Peppers",
                                            "ingredientsAmount": 0,
                                            "howToMake": ""
                                        }
                                    }
                                }
                            }
                        },
                        "description": "Return full details of a given id recipe"
                    },
                    "404": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/error"
                                },
                                "examples": {
                                    "Recipe /w+ was not found": {
                                        "value": "Recipe \\\\w + was not found in game array"
                                    }
                                }
                            }
                        },
                        "description": "Recipe was not found in recipes array"
                    },
                    "500": {
                        "description": "The server encountered an unexpected condition that prevented it from fulfilling the request"
                    }
                },
                "deprecated": false,
                "operationId": "id",
                "summary": "Get full details of a recipe",
                "description": "Return full details of a given id recipe"
            },
            "put": {
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "string"
                            },
                            "examples": {
                                "Update data of a recipe": {
                                    "value": {
                                        "id": 3,
                                        "name": "Chicken Curry",
                                        "ingredientsAmount": 4,
                                        "howToMake": "Buy Chicken and curry paste"
                                    }
                                }
                            }
                        }
                    },
                    "required": true
                },
                "tags": [
                    "recipes"
                ],
                "responses": {
                    "200": {
                        "description": "Updates full details of a given id recipe"
                    },
                    "404": {
                        "description": "Recipe was not found in recipes array"
                    },
                    "500": {
                        "description": "The server encountered an unexpected condition that prevented it from fulfilling the request"
                    }
                },
                "summary": "Update recipe details",
                "description": "Update recipe details"
            },
            "delete": {
                "tags": [
                    "recipes"
                ],
                "parameters": [
                    {
                        "name": "id",
                        "schema": {
                            "type": "integer"
                        },
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No content was found. "
                    },
                    "404": {
                        "description": "Recipe was not found. "
                    },
                    "500": {
                        "description": "The server encountered an unexpected condition that prevented it from fulfilling the request"
                    }
                },
                "summary": "Deletes a recipe",
                "description": "Deletes a recipe by id"
            },
            "parameters": [
                {
                    "name": "id",
                    "schema": {
                        "type": "integer"
                    },
                    "in": "path",
                    "required": true
                }
            ]
        },
        "/ingredients": {
            "get": {
                "tags": [
                    "ingredients"
                ],
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "array",
                                    "items": {
                                        "type": "string"
                                    }
                                },
                                "examples": {
                                    "List of ingredients": {
                                        "value": [
                                            "tomato",
                                            "cucumber"
                                        ]
                                    }
                                }
                            }
                        },
                        "description": "Returns a list of ingredients"
                    },
                    "400": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "array",
                                    "items": {}
                                },
                                "examples": {
                                    "Ingredient not found": {
                                        "value": "New ingredient was not found. "
                                    }
                                }
                            }
                        },
                        "description": "Bad request"
                    },
                    "404": {
                        "description": "Ingredient was not found"
                    },
                    "500": {
                        "description": "The server encountered an unexpected condition that prevented it from fulfilling the request"
                    }
                },
                "summary": "Get a list of all ingredients",
                "description": "Returns a list of all ingredients in API"
            },
            "post": {
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/new-ingredient"
                            }
                        }
                    },
                    "required": true
                },
                "tags": [
                    "ingredients"
                ],
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/new-ingredient"
                                }
                            }
                        },
                        "description": "Request has succeeded"
                    },
                    "201": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/new-ingredient"
                                }
                            }
                        },
                        "description": "New ingredient has been created. "
                    },
                    "400": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/error"
                                }
                            }
                        },
                        "description": "One or all params are missing. "
                    },
                    "500": {
                        "description": "The server encountered an unexpected condition that prevented it from fulfilling the request."
                    }
                },
                "summary": "Creates an ingredient",
                "description": "Creates an new ingredient"
            }
        },
        "/ingredients/{id}": {
            "get": {
                "tags": [
                    "ingredients"
                ],
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "array",
                                    "items": {
                                        "type": "string"
                                    }
                                },
                                "examples": {
                                    "Full details of a given ingredient": {
                                        "value": [
                                            "some text",
                                            "some text"
                                        ]
                                    }
                                }
                            }
                        },
                        "description": "Return full details of a given id ingredient"
                    },
                    "404": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/error"
                                },
                                "examples": {
                                    "Ingredient /w+ was not found": {
                                        "value": "Ingredient\\\\w+ was not found in ingredient array"
                                    }
                                }
                            }
                        },
                        "description": "Ingredient was not found in ingredients array"
                    },
                    "500": {
                        "description": "The server encountered an unexpected condition that prevented it from fulfilling the request"
                    }
                },
                "operationId": "id1",
                "summary": "Get full details of a ingredient",
                "description": "Returns full details of given id ingredient"
            },
            "put": {
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "string"
                            },
                            "examples": {
                                "Update data of an ingredient": {
                                    "value": {
                                        "id": "1",
                                        "name": "cabbage",
                                        "category": "vegetable",
                                        "amount": "5"
                                    }
                                }
                            }
                        }
                    },
                    "required": true
                },
                "tags": [
                    "ingredients"
                ],
                "responses": {
                    "200": {
                        "description": "Updates full details of a given id ingredient"
                    },
                    "404": {
                        "description": "Ingredient was not found in ingedients array"
                    },
                    "500": {
                        "description": "The server encountered an unexpected condition that prevented it from fulfilling the request"
                    }
                },
                "summary": "Update ingredient details",
                "description": "Update ingredient details"
            },
            "delete": {
                "tags": [
                    "ingredients"
                ],
                "responses": {
                    "204": {
                        "description": "No content was found. "
                    },
                    "404": {
                        "description": "Ingredient was not found"
                    },
                    "500": {
                        "description": "The server encountered an unexpected condition that prevented it from fulfilling the request"
                    }
                },
                "summary": "Deletes a ingredient",
                "description": "Deletes a ingredient"
            },
            "parameters": [
                {
                    "name": "id",
                    "schema": {
                        "type": "integer"
                    },
                    "in": "path",
                    "required": true
                }
            ]
        },
        "/users": {
            "description": "",
            "get": {
                "tags": [
                    "users"
                ],
                "responses": {
                    "200": {
                        "description": "Returns all the data related to the users of a recipe "
                    },
                    "500": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "array",
                                    "items": {
                                        "type": "string"
                                    }
                                },
                                "examples": {
                                    "error": {
                                        "value": {
                                            "error": "error message"
                                        }
                                    }
                                }
                            }
                        },
                        "description": "The server encountered an unexpected condition that prevented it from fulfilling the request"
                    }
                },
                "summary": "Gives out a list of users",
                "description": "Gives out a list of users"
            }
        }
    },
    "components": {
        "schemas": {
            "error": {
                "title": "Root Type for error",
                "description": "",
                "type": "object",
                "properties": {
                    "error": {
                        "type": "string"
                    }
                },
                "example": {
                    "error": "Error message."
                }
            },
            "new-recipe": {
                "title": "Root Type for new-recipe",
                "description": "",
                "required": [
                    "howToMake",
                    "ingredientsAmount",
                    "name"
                ],
                "type": "object",
                "properties": {
                    "name": {
                        "type": "string"
                    },
                    "ingredientsAmount": {
                        "format": "int32",
                        "type": "integer"
                    },
                    "howToMake": {
                        "type": "string"
                    },
                    "pictureURL": {
                        "type": "string"
                    }
                },
                "example": {
                    "name": "some text",
                    "ingredientsAmount": 56,
                    "howToMake": "some text"
                }
            },
            "delete-recipe": {
                "description": "",
                "required": [
                    "id"
                ],
                "type": "object",
                "properties": {
                    "id": {
                        "description": "",
                        "type": "string"
                    }
                },
                "example": {
                    "id": 1
                }
            },
            "delete-ingredient": {
                "title": "Root Type for delete-ingredient",
                "description": "",
                "type": "object",
                "properties": {
                    "id": {
                        "format": "int32",
                        "type": "integer"
                    }
                },
                "example": {
                    "id": 1
                }
            },
            "new-ingredient": {
                "title": "Root Type for new-ingredient",
                "description": "",
                "required": [
                    "amount",
                    "category",
                    "name"
                ],
                "type": "object",
                "properties": {
                    "name": {
                        "type": "string"
                    },
                    "category": {
                        "type": "string"
                    },
                    "amount": {
                        "type": "number"
                    }
                },
                "example": {
                    "name": "cabbage",
                    "category": "vegetable",
                    "amount": "5"
                }
            }
        }
    }
}